pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'pwd'
                sh 'sh -x deployment_script.sh'
            }
        }
        stage('Test') { 
            steps {
                sh 'echo "test"'
            }
        }
        stage('Deploy') { 
            steps {
                sh 'echo "Deploy"'
            }
        }
    }
}
