node {
    dir('MainCode') {
        git url: 'https://github.com/Raman-Jaddu/Hello-World.git'    
    }
    stage('Build') {
            sh '''
            pwd
            ls -R
            echo "Build Phase"
            echo "raman"
            '''
     }
     stage('Test') { 
            sh '''
            echo "Test Phase" 
            '''
     }
     stage('Deploy') { 
            sh '''
            echo "deployment Phase" 
            sh BasicDeployments/deployment_script.sh
            '''
     }
    post { 
        always { 
            cleanWs()
        }
    }
}
