pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh '''
                echo "Build Phase"
                '''
            }
        }
        stage('Test') { 
            steps {
                sh '''
                echo "Test Phase" 
                '''
            }
        }
        stage('Deploy') { 
            steps {
                sh '''
                echo "deployment Phase" 
                sh -x BasicDeployments/deployment_script.sh
                '''
            }
        }
    }
}
